### ISSUE TITLE
Some postboxes with out of date collection_times are wrongly displayed with a green icon

### ISSUE THREAD

**Issue by dafadllyn** [1-Byte/swisspost-osm#1]
Hello!

The Swiss Post changed the collection times of most postboxes on 31 May 2021 (see [here](https://www.srf.ch/news/panorama/neue-leerungszeiten-die-meisten-briefkaesten-werden-am-sonntag-nicht-mehr-geleert) (German) and [here](https://www.rts.ch/info/suisse/12252795-la-poste-reduit-la-levee-des-boites-aux-lettres-publiques-vives-reactions.html) (French)). Could you please update your handy tool? This would help a lot to see which and how many postboxes have out of date collection times.

Many thanks in advance!

**Comment by 1-Byte** [comment]
Yes, this was the reason why I created the tool in the first place. According to [saldo](https://www.saldo.ch/artikel/artikeldetail/schluss-mit-a-post-in-vielen-ortschaften/) (German, paywall), the new collection times are listed on [places.post.ch](https://places.post.ch). The tool fetches the collection times from this site automatically.

The OSM data is fetched from the [Swiss Overpass API](https://overpass-turbo.osm.ch/) which might be delayed a few hours.

Do you have an example where the data available online does not match what's shown in front of the letter box?

**Comment by dafadllyn** [comment]
These examples have wrong collection times, but are displayed with a green location pin:

* https://www.openstreetmap.org/node/3225376549 – OSM: Mo-Fr 17:00; Sa 07:00 – post.ch: Monday - Friday 10.00
* https://www.openstreetmap.org/node/703577454 – OSM: Mo-Fr 17:00; Sa 07:00 – post.ch: Monday - Friday 18.00
* https://www.openstreetmap.org/node/1721178772 – OSM: Mo-Fr 17:00; Sa 07:00 – post.ch: Monday - Friday 17.00

**Comment by 1-Byte** [comment]
I hope that with the change to blue icons (see #2), we can avoid the confusion of implying green = good. What do you think?

**Comment by dafadllyn** [comment]
Now i'm confused: the blue (formerly green) marker is displayed for:

* postboxes with up to date collection times ([example](https://www.openstreetmap.org/node/3281197935))
* postboxes with outdated collection times ([example](https://www.openstreetmap.org/node/1988811409))
* postboxes that no longer exist ([example](https://www.openstreetmap.org/node/2480116849))

Other postboxes with outdated collection times ([example](https://www.openstreetmap.org/node/6689607754)) are displayed with a yellow-blue marker. (Purely yellow markers seem to indicate missing postboxes.)

Something must be wrong.

**Comment by 1-Byte** [comment]
I'm sorry for not being to able to clear up the confusion. To avoid excessive data scraping, the tool doesn't evaluate the data before the popup opens. For the time being, I added a legend to explain what the marker colors signify and will investigate on how we could evaluate data eagerly.

**Comment by dafadllyn** [comment]
Thanks for adding the legend, which cleared up my confusion! Please excuse my confusion.
