### ISSUE TITLE
Feature request: mark removed postboxes

### ISSUE THREAD

**Issue by dafadllyn** [1-Byte/swisspost-osm#2]
It would be helpful if postboxes that no longer exist were marked.

**Comment by 1-Byte** [comment]
Do you have an example of such a postbox? Is it still present in OSM or on https://places.post.ch/ (or both)?

**Comment by dafadllyn** [comment]
For example, the following postboxes are no longer present in https://places.post.ch but still present in OSM:

* https://www.openstreetmap.org/node/2480116849
* https://www.openstreetmap.org/node/4810844322
* https://www.openstreetmap.org/node/5122211447

However, they have a green location icon. It would be helpful if the icon were red or grey.

**Comment by 1-Byte** [comment]
Oh, I see, my color choice for the OSM icons was unfortunate. I changed them to blue which means if you see a purely blue marker, it's likely no longer in service.

**Comment by dafadllyn** [comment]
See #1. This feature request is no longer relevant.
