### ISSUE TITLE
Feature request: add pop-up info boxes for blue markers

### ISSUE THREAD

**Issue by dafadllyn** [1-Byte/swisspost-osm#4]
Could you please add pop-up info boxes for the blue markers? This would be especially helpful for places where  a yellow and blue marker are right next to each other. (In [some](https://www.openstreetmap.org/node/3281266532) [places](https://www.openstreetmap.org/node/3223975064) the position from the Swiss Post is quite imprecise.)

**Comment by 1-Byte** [comment]
Yes :+1: the popup is available for all markers now.

**Comment by dafadllyn** [comment]
Thanks a lot!
